[package]
# Semantic Versionning is used: https://semver.org/
version = "0.2.2"

# The title and description fields are primarily for displaying extension info in UI
title = "Warehouse Creator"
description="A simple extension to randomly generate warehouse environments."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"

# URL of the extension source repository.
repository = ""

icon = "data/icon.png"
# One of categories for UI.
category = "Warehouse Creator"

# Keywords for the extension
keywords = ["kit", "digitaltwin", "warehouse", "generate"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.warehouse_creator"
